esphome:
  name: tcl-ac

esp8266:
  board: esp07

external_components:
  - source:
      type: git
      url: https://github.com/lNikazzzl/tcl_climate
    components: [ tcl_climate ]
#  or local
#  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  password: 123

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  parity: EVEN

logger:
  level: VERBOSE
  baud_rate: 0

climate:
  - platform: tcl_climate
    id: tcl_custom_climate
    uart_id: uart_bus
    name: "HAVC TCL"

select:
  - platform: template
    name: Vertical swing
    id: vswing
    entity_category: config
    options:
      - "Last position"
      - "Fix top"
      - "Fix upper"
      - "Fix mid"
      - "Fix lower"
      - "Fix bottom"
      - "Move full"
      - "Move upper"
      - "Move lower"
    set_action:
      then:
        lambda: |-
            id(tcl_custom_climate).control_vertical_swing(x);

  - platform: template
    name: Horizontal swing
    id: hswing
    entity_category: config
    options:
      - "Last position"
      - "Fix left"
      - "Fix mid left"
      - "Fix mid"
      - "Fix mid right"
      - "Fix right"
      - "Move full"
      - "Move left"
      - "Move mid"
      - "Move right"
    set_action:
      then:
        lambda: |-
            id(tcl_custom_climate).control_horizontal_swing(x);
